repositories:
  Local Photos 1:
    type: local
    root: ./local/photos1
    enabled: true
  Local Photos 2:
    type: local
    root: ./local/photos2
    enabled: false
  Local Frankreich:
    type: local
    root: ./local/frankreich
    enabled: false
  Local Videos:
    type: local
    root: ./local/videos
    enabled: false
  WebDav Photos:
    type: webdav
    url: https://cloud.rueblitorte.de
    root: /remote.php/webdav/Photos
    user: pyframe
    password: 61wEKZ549c74q3P6
    enabled: false

slideshow:
  sequence: random
#  order: ascending
  orientation: landscape
#  mostRecent: 5
  fileType:
    - videos
    - images
#  tags: 2019-08 Südfrankreich
#    - lilith
  pause: 5

index: ./index.sqlite"
cache: ./cache
rotation: 0
bgcolor: [1,1,1]
